name: Generate Proposal Summaries

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering
  push:
    paths:
      - "summarize.py"
      - ".github/workflows/summarize_EIPs.yml"

jobs:
  generate-summaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Clone Ethereum repositories
        run: |
          git clone https://github.com/ethereum/EIPs.git ethereum-eips
          git clone https://github.com/ethereum/ERCs.git ethereum-ercs

      - name: Run summarizer for EIPs
        run: |
          python ./ethereum/summarize.py --type eip --input-dir ./ethereum-eips/EIPS --output-dir ./ethereum

      - name: Run summarizer for ERCs
        run: |
          python ./ethereum/summarize.py --type erc --input-dir ./ethereum-ercs/ERCS --output-dir ./ethereum

      - name: Commit and push if changes exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add summaries/
          git diff --staged --quiet || (git commit -m "Auto-update proposal summaries" && git push)
